[tasks.clean]
description = "Clean proyect"
command = "cargo"
args = ["clean"]


[tasks.build]
command = "cargo"
args = ["build"]



[tasks.test]
command = "cargo"
args = ["test"]


[tasks.run]
command = "cargo"
args = ["run"]

[tasks.docgenerate]
command = "cargo"
args = ["doc","-p","cloudbanking", "--no-deps"]

[tasks.release]
command = "cargo"
args = ["build", "--release", "--bin", "CloudBanking"]

[tasks.doc]
script = [
    "echo $PWD",
    "cp -rf target/doc/cloudbanking docs/documentation/cloudbanking",
    "cp target/doc/*.woff docs/documentation/",
    "cp target/doc/settings.html docs/documentation/",
    "cp target/doc/*.css docs/documentation/",
    "cp target/doc/*.ico docs/documentation/",
    "cp target/doc/*.png docs/documentation/",
    "cp target/doc/*.js docs/documentation/",
    "cp target/doc/*.svg docs/documentation/",
]
dependencies = ["docgenerate"]


[tasks.dirtree]
script = [
    "find Gemfile README.md cc.yaml  make.toml LICENSE _config.yml src install makefile .github/workflows .gitignore .travis.yml  -type f |  cut -d/ -f-4 | uniq  |  dirtree -o docs/dirtree.html"
]
