# This is a basic workflow to help you get started with Actions

name: MicroserviceTest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install ysh
        run: |
          sudo curl -s -L https://raw.githubusercontent.com/azohra/yaml.sh/v0.2.0/ysh --output /usr/bin/ysh
          sudo chmod +x /usr/bin/ysh
      - name: Extract make key and save value in $MAKE
        run: |
          ysh -f cc.yaml -q "make"
          MAKE=$(ysh -f cc.yaml -q "make")
          echo $MAKE
          MAKE2="${MAKE//\"}"
          echo "Finally I will use"
          echo $MAKE2
      - name: Generate Docker Commands
        run: |
          INSTALL="${MAKE2} install" 
          BUILD="${MAKE2} build"
          TEST="${MAKE2} test"
          
          echo "My commands are:"
          echo $INSTALL
          echo $BUILD
          echo $TEST

      - name: Ejecuta contenedor
        run: |
          docker run -t -v `pwd`:/app/test pepitoenpeligro/cloudbanking sh -c "${INSTALL} && ${BUILD} && ${TEST}"
