# This is a basic workflow to help you get started with Actions

name: MicroserviceTest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ysh
        run: |
          sudo curl -s -L https://raw.githubusercontent.com/azohra/yaml.sh/v0.2.0/ysh --output /usr/bin/ysh
          sudo chmod +x /usr/bin/ysh
      - name: Extract make key and save value in $MAKE
        id: extract_make
        run: |
          ysh -f cc.yaml -q "make"
          MAKE=$(ysh -f cc.yaml -q "make")
          echo $MAKE
          MAKE2="${MAKE//\"}"
          echo "Finally I will use"
          echo $MAKE2
          echo "I recover ${MAKE2}"
          INSTALL="${MAKE2} install" 
          BUILD="${MAKE2} build"
          TEST="${MAKE2} test"
          echo "My commands are:"
          echo ${INSTALL}
          echo ${BUILD}
          echo ${TEST}
          echo "Finally I will inject: "
          # COMMAND=echo "${INSTALL} && ${BUILD} && ${TEST}"
          echo "${INSTALL} && ${BUILD} && ${TEST}"
          docker run -t -v `pwd`:/app/test pepitoenpeligro/cloudbanking sh -c " ${INSTALL} && ${BUILD} && ${TEST} "
