# This is a basic workflow to help you get started with Actions

name: "Check cc.yaml file"

on:
  push:
    branches: [ master ]
    paths:
      - 'cc.yaml'
  pull_request:
    branches: [ master ]
    paths:
      - 'cc.yaml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Esto fallar√° si no existe
      - name: YAML Lint
        run: yamllint cc.yaml

      - name: Check -entidad- existence
        id: check-entidad-cc-yaml
        run: |
          for s in entidad lenguaje test fichero_tareas
          do
              grep -c ${s} cc.yaml


