name: cloudbanking proyect test (ci)

on:
  push:
    branches: 
      - 'master'
      - 'hito*'
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # List of possible runners 
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      # Smart Cache for rust
      # https://github.com/Swatinem/rust-cache
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --nocapture
