name: "Crea artefacto con configuraciÃ³n"
on:
  workflow_run:
    workflows: ["Check cc.yaml file"]
    types: completed

jobs:
  sube_config:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga contenidos
        uses: actions/checkout@v2
      - name: Descarga ysh
        run: |
          sudo curl -s -L https://raw.githubusercontent.com/azohra/yaml.sh/v0.2.0/ysh --output /usr/bin/ysh
          sudo chmod +x /usr/bin/ysh
      - name: Procesa fichero
        run: |
          cc=$(ysh -f cc.yaml)
          lenguaje=$(ysh -T $cc -q "lenguaje")
          fichero_tareas=$(ysh -T $cc -q "fichero_tareas")
          echo "CC_LENGUAJE=$lenguaje" >> CC_CONFIG
          echo "CC_FICHERO_TAREAS=$fichero_tareas" >> CC_CONFIG
      - name: "Sube el fichero"
        uses: actions/upload-artifact@v2
        with:
          name: cc-config
          path: CC_CONFIG

